// 07Vue/19_脚手架/37_src_编程式路由导航/pages/Home.vue
<template>
  <div>
    <h2>我是Home的内容</h2>
    <ul class="nav nav-tabs">
      <li>
        <router-link class="list-group-item" active-class="active" to="/home/news">News</router-link>
      </li>
      <li>
        <router-link class="list-group-item " active-class="active" to="/home/message">Message</router-link>
      </li>
    </ul>
    <!-- 指定组件的呈现位置 -->
    <router-view></router-view>
  </div>
</template>

<script>
  export default {
    name:"Home",
    beforeDestroy() {
      console.log("About组件即将被销毁了");
    },
    mounted() {
      console.log("Home组件挂载完毕了",this);
    },
  }
</script>

// 08React/react_router_6/src/pages/Home.jsx
import React from 'react'
import { NavLink,Outlet } from "react-router-dom";

export default function Home() {
  return (
    <div>
      <h2>Home组件内容</h2>
      <div>
        <ul className="nav nav-tabs">
          <li>
            {/* 可以去掉/home/ */}
            <NavLink className="list-group-item" to="news">News</NavLink>
          </li>
          <li>
            {/* 可以去掉/home/ */}
            <NavLink className="list-group-item" to="message">Message</NavLink>
          </li>
        </ul>
        {/* 指定路由组件的呈现位置 */}
        <Outlet/>
      </div>
    </div>
  )
}
