// BBT/07Vue/19_脚手架/23_src_求和案例_纯vue版/components/Count.vue
<template>
  <div>
    <h1>当前求和为：{{ sum }}</h1>
      <select v-model.number="n">
        <option :value="1">1</option>
        <option :value="2">2</option>
        <option :value="3">3</option>
      </select>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementOdd">当前求和为奇数再加</button>
    <button @click="incrementWait">等一等再加</button>
  </div>
</template>

<script>
  export default {
    name: "Count",
    data(){
      return{
        n: 1, //用户选择的数字
        sum: 0 //当前的和
      }
    },
    methods:{
      increment(){
        this.sum += this.n
      },
      decrement(){
      this.sum -= this.n
      },
      incrementOdd(){
        if(this.sum % 2){
          this.sum += this.n
        }
      },
      incrementWait(){
        setTimeout(()=>{
          this.sum += this.n
        },500)
      }
    }
  }
</script>

<style>
  button{
    margin-left: 5px;
  }
</style>

// 08React/redux_test/src/components/Count/index.jsx
import React, { Component } from 'react'

export default class Count extends Component {
  state = {count:0}
  // 加法
  increment = ()=>{
    const {value} = this.selectNumber
    const {count} = this.state
    this.setState({count:count+value*1})
  }
  // 减法
  decrement = ()=>{
    const {value} = this.selectNumber
    const {count} = this.state
    this.setState({count:count-value*1})
  }
  // 奇数再加
  incrementIfOdd = ()=>{
    const {value} = this.selectNumber
    const {count} = this.state
    if(count % 2 !== 0){
      this.setState({count:count+value*1})
    }
  }
  incrementAsync = ()=>{
    const {value} = this.selectNumber
    const {count} = this.state
    setTimeout(() => {
      this.setState({count:count+value*1})
    }, 500);
  }
  render() {
    return (
      <div>
        <h1>当前求和为：{this.state.count}</h1>
        {/* ref 用于取当前元素，c代指当前DOM节点 */}
        <select ref={c => this.selectNumber = c}>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
        </select>&nbsp;
        <button onClick={this.increment}>+</button>&nbsp;
        <button onClick={this.decrement}>-</button>&nbsp;
        <button onClick={this.incrementIfOdd}>当前求和为奇数再加</button>&nbsp;
        <button onClick={this.incrementAsync}>异步加</button>
      </div>
    )
  }
}
