// BBT/07Vue/19_脚手架/28_src_求和案例_多组件共享数据/components/Person.vue
<template>
  <div>
    <h1>人员列表</h1>
    <h3 style="color: red;">Count求和为：{{ sum }}</h3>
    <input type="text" placeholder="请输入名字" v-model="name">
    <button @click="add">添加</button>
    <ul>
      <li v-for="p in personList" :key="p.id">{{p.name}}</li>
    </ul>
  </div>
</template>

<script>
  import { nanoid } from 'nanoid'
  import { mapState } from 'vuex'
  export default {
    name: "Person",
    data(){
      return {
        name:''
      }
    },
    computed:{
      //...mapState(['personList'])
      personList(){
        return this.$store.state.personList
      },

      sum(){
        return this.$store.state.sum
      }
    },
    methods:{
      add(){
        const personObj = {id:nanoid(),name:this.name}
        this.$store.commit('ADD_PERSON',personObj)
        // console.log(personObj);
        this.name = ''
      }
    }
  }
</script>

// BBT/08React/redux_test/src/containers/Person/index.jsx
import React, { Component } from 'react'
import {nanoid} from 'nanoid'

export default class Person extends Component {

  addPerson= ()=>{
    const name = this.nameNode.value
    const age = this.ageNode.value
    //console.log(name,age);
    const personObj = {id:nanoid(),name,age}
    console.log(personObj);
  }

  render() {
    return (
      <div>
        <h2>我是person组件</h2>
        <input ref={c => this.nameNode = c} type="text" placeholder='输入名字'></input>
        <input ref={c => this.ageNode = c} type="text" placeholder='输入年龄'></input>
        <button onClick={this.addPerson}>添加</button>
        <ul>
          <li>1</li>
          <li>2</li>
          <li>3</li>
        </ul>
      </div>
    )
  }
}
