// BBT/07Vue/19_脚手架/src/pages/Detail.vue
<template>
  <ul>
    <!-- <li>消息编号：{{ $route.params.id }}</li>
    <li>消息标题：{{ $route.params.title }}</li> -->

    <!-- 计算属性的写法 -->
    <!-- <li>消息编号：{{ id }}</li>
    <li>消息标题：{{ title }}</li> -->

    <!-- props 第一种写法 -->
    <!-- <li>消息编号：{{ a }}</li>
    <li>消息标题：{{ b }}</li> -->

    <!-- props 第二种写法 -->
    <li>消息编号：{{ id }}</li>
    <li>消息标题：{{ title }}</li>
  </ul>
</template>

<script>
  export default {
    name:'Detail',
    //props 第一种写法
    // props:['a','b'],

    //props 第二种写法
    props:['id','title'],

    //计算属性的写法
    // computed:{
    //   id(){
    //     return this.$route.params.id
    //   },
    //   title(){
    //     return this.$route.params.title
    //   }
    // },
    mounted() {
      console.log(this.$route);
    },
  }
</script>

<style>

</style>

// BBT/08React/react_router_6/6_src_路由的params参数/pages/Detail.jsx
import React from 'react'
import { useParams,useMatch } from 'react-router-dom'

export default function Detail() {
  const {id,title,content} = useParams()//useParams返回父组件传的所有参数
  const x = useMatch('/home/message/detail/:id/:title/:content')
  console.log(x.params);//useMatch相当于类式组件的this.props.match.params，用起来不如useParams方便
  return (
    <div>
      <ul>
        <li>消息编号：{id}</li>
        <li>消息标题：{title}</li>
        <li>消息内容：{content}</li>
      </ul>
    </div>
  )
}
