// 08React/react_router_6/01_src_一级路由/App.js
import React from 'react'
import {NavLink,Routes,Route} from 'react-router-dom' //新版本Routes替代Switch
import About from './pages/About'
import Home from './pages/Home'

export default function App() {
  return (
    <div>
      <div className="row">
        <div className="col-xs-offset-2 col-xs-8">
          <div className="page-header"><h2>React Router Demo</h2></div>
        </div>
      </div>
      <div className="row">
        <div className="col-xs-2 col-xs-offset-2">
          <div className="list-group">
            {/* 路由链接 */}
            <NavLink className="list-group-item" to="/about">About</NavLink>
            <NavLink className="list-group-item active" to="/home">Home</NavLink>
          </div>
        </div>
        <div className="col-xs-6">
          <div className="panel">
            <div className="panel-body">
              {/* 注册路由 */}
              {/* 新版本Routes替代Switch */}
              <Routes>
                {/* 新版本element替代component */}
                <Route path="/about" element={<About/>}/>
                <Route path="/home" element={<Home/>}/>
              </Routes>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// BBT/07Vue/19_脚手架/35_src_路由的props参数/App.vue
<template>
  <div>
    <div class="row">
      <Banner/>
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <!-- 原始html中我们使用a标签实现页面的跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

          <!-- Vue中借助router-link标签实现路由的切换 -->
          <!-- router-link本质也是a标签 -->
          <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
          <!-- 下面是另外一种写法name -->
          <!-- <router-link class="list-group-item" active-class="active" :to="{name:'about'}">About</router-link> -->

          <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <!-- 指定组件的呈现位置 -->
            <router-view></router-view>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Banner from './components/Banner.vue'
  export default {
    name: "App",
    components:{Banner}
  };
</script>
